use std::collections::HashMap;
use std::net::SocketAddr;
use std::path::{Path as FsPath, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::time::Duration;

use axum::extract::{Path, Query, State};
use axum::routing::get;
use axum::Router;
use axum_extra::headers::Range;
use axum_extra::TypedHeader;
use axum_range::{KnownSize, Ranged};
use librqbit::api::{Api, TorrentIdOrHash};
use librqbit::{AddTorrent, AddTorrentOptions, AddTorrentResponse, Session};
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex as AsyncMutex;

/// librqbit's `TorrentId` type alias (`usize`) isn't re-exported from the
/// crate root, so we mirror it here rather than depend on a private path.
pub type TorrentId = usize;

/// HLS segment length. 6s is Apple's low-latency recommendation.
const SEGMENT_DURATION_SECONDS: f64 = 6.0;

/// How many segments a request is allowed to sit ahead of a job's current
/// on-disk progress before that's treated as a real seek (worth killing and
/// restarting the transcode at the new offset) rather than normal
/// hls.js/browser prefetch that will be satisfied by the job's own
/// sequential progress shortly. ~2 minutes at `SEGMENT_DURATION_SECONDS`.
const RESTART_LOOKAHEAD_SEGMENTS: usize = 20;

/// How long a segment request waits for the transcode job to produce the
/// file before giving up - bounded mostly by torrent download speed, not
/// transcode speed, since `ffmpeg` blocks on `stream_handler` for
/// not-yet-downloaded bytes.
const SEGMENT_WAIT_TIMEOUT: Duration = Duration::from_secs(45);
const SEGMENT_POLL_INTERVAL: Duration = Duration::from_millis(250);

pub struct TorrentEngine {
    session: Arc<Session>,
    api: Api,
    stream_addr: SocketAddr,
    hls_jobs: HlsJobs,
}

/// One in-progress `ffmpeg` HLS transcode for a specific torrent file -
/// see `HlsJobs` for why there's at most one of these per file and how
/// requests decide whether to reuse or restart it.
struct HlsJob {
    child: tokio::process::Child,
    dir: PathBuf,
    /// The segment index this job was told to start at (via `-ss`/
    /// `-start_number`) - segment requests below this were generated by an
    /// *earlier* job run and, if missing, need a fresh restart to fill the
    /// gap rather than waiting on this job to ever produce them.
    start_index: usize,
}

/// Tracks the single running (or most recently run) `ffmpeg` transcode job
/// per torrent file, keyed so unrelated files never block each other's
/// decisions while same-file requests serialize on one lock.
///
/// Replaces an earlier design that spawned an independent `ffmpeg -ss
/// ... -t 6 ...` process per *segment*: each one reinitialized its own AAC
/// encoder and re-based timestamps from zero, which produced audible
/// discontinuities at every segment boundary and, since `-ss` before `-i`
/// only approximately seeks without a Matroska Cues index (not available
/// on a still-downloading torrent), sometimes fed the muxer inconsistent
/// timestamps outright ("Error submitting a packet to the muxer: Invalid
/// argument" - verified live). A single continuous `ffmpeg` process per
/// file reading sequentially from byte 0 has one continuous encoder/
/// timestamp timeline for the whole episode, and its sequential HTTP reads
/// line up naturally with librqbit's own sequential piece-priority
/// download strategy instead of fighting it with scattered probe reads.
#[derive(Clone)]
struct HlsJobs {
    jobs: Arc<AsyncMutex<HashMap<(TorrentId, usize), Arc<AsyncMutex<Option<HlsJob>>>>>>,
    cache_root: PathBuf,
}

impl HlsJobs {
    fn new(cache_root: PathBuf) -> Self {
        Self { jobs: Arc::new(AsyncMutex::new(HashMap::new())), cache_root }
    }

    fn job_dir(&self, torrent_id: TorrentId, file_idx: usize) -> PathBuf {
        self.cache_root.join(format!("{torrent_id}_{file_idx}"))
    }

    fn segment_path(&self, torrent_id: TorrentId, file_idx: usize, segment_index: usize) -> PathBuf {
        self.job_dir(torrent_id, file_idx).join(format!("{segment_index}.ts"))
    }

    async fn key_lock(&self, torrent_id: TorrentId, file_idx: usize) -> Arc<AsyncMutex<Option<HlsJob>>> {
        let mut jobs = self.jobs.lock().await;
        jobs.entry((torrent_id, file_idx)).or_insert_with(|| Arc::new(AsyncMutex::new(None))).clone()
    }

    /// How far into the file playback can seek and get an instant response
    /// (backed by an already-produced segment file), as a timestamp in
    /// seconds - not to be confused with raw torrent download progress.
    /// Those two track different things and can diverge a lot: a byte
    /// range can be fully downloaded while its segment still needs ffmpeg
    /// to actually process it, and a restart-at-a-seek-target can leave
    /// large already-transcoded stretches behind at a lower index than the
    /// current job's own start_index (still instantly seekable, just not
    /// "in progress" by the sense HlsJob::start_index tracks) - so this
    /// deliberately scans for the highest segment file across the whole
    /// directory, unlike the restart-decision logic elsewhere in this
    /// impl, which only looks at the *current* job's own progress.
    fn ready_seconds(&self, torrent_id: TorrentId, file_idx: usize) -> f64 {
        let dir = self.job_dir(torrent_id, file_idx);
        let Ok(entries) = std::fs::read_dir(&dir) else {
            return 0.0;
        };
        let highest = entries
            .flatten()
            .filter_map(|entry| {
                entry.file_name().to_str().and_then(|name| name.strip_suffix(".ts")).and_then(|stem| stem.parse::<usize>().ok())
            })
            .max();
        match highest {
            Some(index) => (index + 1) as f64 * SEGMENT_DURATION_SECONDS,
            None => 0.0,
        }
    }

    /// Ensures a background transcode job is producing (or has already
    /// produced) the segment at `segment_index`, restarting it at that
    /// offset first if needed, then waits for the resulting file to land
    /// on disk.
    async fn ensure_segment_available(
        &self,
        torrent_id: TorrentId,
        file_idx: usize,
        segment_index: usize,
        stream_addr: SocketAddr,
    ) -> anyhow::Result<PathBuf> {
        let path = self.segment_path(torrent_id, file_idx, segment_index);
        if tokio::fs::try_exists(&path).await.unwrap_or(false) {
            return Ok(path);
        }

        let job_lock = self.key_lock(torrent_id, file_idx).await;
        {
            let mut job_slot = job_lock.lock().await;
            let needs_restart = match job_slot.as_ref() {
                None => true,
                Some(job) => {
                    // Only counts files at or after this job's own
                    // start_index - the directory isn't cleared on
                    // restart, so lower-numbered segments from an earlier,
                    // already-superseded run can still be sitting there.
                    // Counting those as "progress" made a request for a
                    // fresh restart's own (not-yet-produced) target look
                    // like it was still far ahead of "current progress",
                    // triggering another pointless restart to the exact
                    // same offset - verified live: a single seek restarted
                    // the job 5+ times in a row before it was ever left
                    // alone long enough to produce a single segment.
                    let highest_existing = highest_existing_segment_from(&job.dir, job.start_index).await.unwrap_or(job.start_index);
                    // Below the current job's start: it belongs to an
                    // earlier, already-superseded run and was never
                    // produced (a backward seek into a gap a forward seek
                    // left behind). Far enough ahead of current progress
                    // that it's clearly a real seek, not prefetch the job
                    // will reach shortly on its own.
                    segment_index < job.start_index || segment_index > highest_existing + RESTART_LOOKAHEAD_SEGMENTS
                }
            };

            if needs_restart {
                if let Some(mut old) = job_slot.take() {
                    let _ = old.child.start_kill();
                    tracing::info!(torrent_id, file_idx, "killed hls transcode job to restart at a new offset");
                }
                let dir = self.job_dir(torrent_id, file_idx);
                tokio::fs::create_dir_all(&dir).await?;
                let child = spawn_hls_transcode(torrent_id, file_idx, segment_index, stream_addr, &dir)?;
                *job_slot = Some(HlsJob { child, dir, start_index: segment_index });
                tracing::info!(torrent_id, file_idx, segment_index, "started hls transcode job");
            }
        }

        let wait_started = tokio::time::Instant::now();
        let deadline = wait_started + SEGMENT_WAIT_TIMEOUT;
        while tokio::time::Instant::now() < deadline {
            if tokio::fs::try_exists(&path).await.unwrap_or(false) {
                // Diagnostic for "seeking is slow" reports: distinguishes a
                // slow torrent download (this job just started, most of
                // the wait was here) from a slow restart/ffmpeg-startup
                // path (this fires almost immediately after the "started
                // hls transcode job" log line above).
                tracing::debug!(
                    torrent_id,
                    file_idx,
                    segment_index,
                    wait_ms = wait_started.elapsed().as_millis() as u64,
                    "hls segment became available"
                );
                return Ok(path);
            }
            {
                // Bail out early if the job already died rather than
                // waiting out the full timeout for a file it will never
                // produce (e.g. the underlying torrent stream errored).
                let mut job_slot = job_lock.lock().await;
                if let Some(job) = job_slot.as_mut() {
                    if let Ok(Some(status)) = job.child.try_wait() {
                        anyhow::bail!("hls transcode process for segment {segment_index} exited early with {status}");
                    }
                }
            }
            tokio::time::sleep(SEGMENT_POLL_INTERVAL).await;
        }
        anyhow::bail!("timed out waiting for hls segment {segment_index} to be generated")
    }

    /// Kills and forgets any transcode job for `torrent_id` (any file
    /// index) and deletes its cached segments - called when the torrent
    /// itself is removed so nothing keeps writing into a now-orphaned
    /// cache directory.
    async fn remove_torrent(&self, torrent_id: TorrentId) {
        let mut jobs = self.jobs.lock().await;
        let keys: Vec<_> = jobs.keys().filter(|(id, _)| *id == torrent_id).cloned().collect();
        for key in keys {
            if let Some(job_lock) = jobs.remove(&key) {
                let mut job_slot = job_lock.lock().await;
                if let Some(mut job) = job_slot.take() {
                    let _ = job.child.start_kill();
                    let _ = tokio::fs::remove_dir_all(&job.dir).await;
                }
            }
        }
    }
}

/// Highest `.ts` segment index present in `dir` at or after `min_index` -
/// callers pass the current job's own `start_index` so a lower-numbered
/// leftover from an earlier, already-superseded job run (the directory is
/// never cleared on restart) can't be mistaken for that job's own progress.
async fn highest_existing_segment_from(dir: &FsPath, min_index: usize) -> Option<usize> {
    let mut entries = tokio::fs::read_dir(dir).await.ok()?;
    let mut highest = None;
    while let Ok(Some(entry)) = entries.next_entry().await {
        if let Some(index) = entry
            .file_name()
            .to_str()
            .and_then(|name| name.strip_suffix(".ts"))
            .and_then(|stem| stem.parse::<usize>().ok())
        {
            if index >= min_index {
                highest = Some(highest.map_or(index, |h: usize| h.max(index)));
            }
        }
    }
    highest
}

/// Spawns the single continuous `ffmpeg` process for a torrent file's HLS
/// transcode, starting at `start_segment_index` (0 for normal sequential
/// playback from the beginning, non-zero only when restarting at a seek
/// target). Reads from `stream_handler` over loopback rather than the
/// downloaded file directly, reusing its existing Range-aware,
/// piece-priority-aware blocking reads instead of teaching `ffmpeg` about
/// librqbit's growing sparse file. Writes segments as real files
/// (`-hls_flags temp_file` renames each into place only once complete, so
/// a segment request never sees a partially-written file) rather than
/// piping to a per-request process - see `HlsJobs`' doc comment for why
/// this replaced the old one-`ffmpeg`-per-segment design.
fn spawn_hls_transcode(
    torrent_id: TorrentId,
    file_idx: usize,
    start_segment_index: usize,
    stream_addr: SocketAddr,
    dir: &FsPath,
) -> anyhow::Result<tokio::process::Child> {
    let start_seconds = start_segment_index as f64 * SEGMENT_DURATION_SECONDS;
    let input_url = format!("http://{stream_addr}/stream/{torrent_id}/{file_idx}");
    let segment_filename = dir.join("%d.ts");
    // ffmpeg's own playlist output is discarded - hls_playlist_handler
    // still serves the frontend-duration-derived playlist described
    // there; we only want this process's segment files.
    let discarded_playlist_path = dir.join("ffmpeg_internal.m3u8");

    let mut command = tokio::process::Command::new("ffmpeg");
    command.args(["-loglevel", "warning"]);
    // Sequential playback from the start (the overwhelmingly common case)
    // deliberately omits `-ss` entirely rather than passing `-ss 0`: with
    // no Matroska Cues index available on a still-downloading torrent, any
    // `-ss` at all can make ffmpeg attempt a byte-offset seek estimate
    // instead of just reading forward from the response's first byte.
    if start_seconds > 0.0 {
        command.args(["-ss", &start_seconds.to_string()]);
    }
    command.args(["-i", &input_url]);
    command.args([
        // Real releases commonly carry an embedded subtitle track (e.g.
        // WebVTT) alongside video/audio. MPEG-TS/HLS can't carry that
        // (there's no subtitle UI here to feed it to anyway), and leaving
        // ffmpeg to auto-select "best of every stream type" made it try
        // to mux the subtitle track into the TS output anyway, which
        // spammed non-monotonic-DTS warnings and was implicated in at
        // least one dropped segment (a muxer "Invalid argument" error) -
        // verified live. Mapping exactly one video and one audio stream
        // and nothing else avoids the whole class of problem.
        "-map",
        "0:v:0",
        "-map",
        "0:a:0",
        "-sn",
        "-c:v",
        "copy",
        // Audio is always transcoded to AAC rather than copied: several
        // codecs real releases use (e.g. E-AC-3) aren't reliably muxable
        // into MPEG-TS/played back by browsers, and AAC is universally
        // supported. A single continuous encoder instance for the whole
        // file (unlike the old per-segment approach) keeps its timestamp
        // timeline continuous, which is what actually fixes the audio
        // artifacts at segment boundaries.
        "-c:a",
        "aac",
        "-f",
        "hls",
        "-hls_time",
        &SEGMENT_DURATION_SECONDS.to_string(),
        "-hls_list_size",
        "0",
        "-hls_flags",
        "temp_file+independent_segments",
        "-start_number",
        &start_segment_index.to_string(),
        "-hls_segment_filename",
    ]);
    command.arg(segment_filename.to_string_lossy().to_string());
    command.arg(discarded_playlist_path.to_string_lossy().to_string());

    let mut child = command
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| anyhow::anyhow!("failed to spawn ffmpeg for hls transcode (is it installed and on PATH?): {err}"))?;

    if let Some(stderr) = child.stderr.take() {
        tokio::spawn(async move {
            use tokio::io::{AsyncBufReadExt, BufReader};
            let mut lines = BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                tracing::warn!(torrent_id, file_idx, ffmpeg_stderr = %line, "ffmpeg hls transcode stderr");
            }
        });
    }

    Ok(child)
}

pub struct AddedTorrent {
    pub id: TorrentId,
}

#[derive(Clone)]
struct StreamRouterState {
    api: Api,
    stream_addr: SocketAddr,
    hls_jobs: HlsJobs,
}

/// Trimmed-down mirror of librqbit's `TorrentStats` - mirrors Stremio's own
/// streaming-server statistics endpoint (`GET /:infoHash/stats.json`,
/// see `reference/stremio-core`'s `models::streaming_server`), which the
/// player UI polls to show download progress/speed/peers while a stream is
/// buffering, rather than leaving the user staring at a blank window with
/// no feedback while mpv waits for enough data to start decoding.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StreamStats {
    /// "initializing" | "live" | "paused" | "error"
    pub state: String,
    pub progress_percent: f64,
    /// Despite the name, librqbit's underlying `Speed::mbps` field is
    /// actually MiB/s (see its `Display` impl) - mirrored as-is here.
    pub download_speed_mbps: f64,
    pub connected_peers: u32,
    pub finished: bool,
    /// Raw byte counts (alongside `progress_percent`) so the frontend can
    /// port stremio-web's own weighted buffering-readiness score
    /// (`useStatistics.ts`'s `getLoadingProgress`: peers/downloaded-vs-
    /// threshold/speed, not just raw completion percent) rather than a
    /// cruder "% of the whole file" estimate.
    pub downloaded_bytes: u64,
    pub total_bytes: u64,
    /// How far into the file (in seconds) HLS segments have actually been
    /// produced and are ready for an instant seek - see
    /// `HlsJobs::ready_seconds`'s doc comment for why this isn't the same
    /// thing as `progress_percent`. Frontend seek-bar highlight should use
    /// this, not `progress_percent`, for "can I seek here instantly".
    pub ready_seconds: f64,
}

impl TorrentEngine {
    /// Starts a librqbit session rooted at `download_dir` and a local HTTP
    /// server that serves torrent file bytes with Range support, mirroring
    /// Stremio's local streaming server.
    pub async fn start(download_dir: PathBuf) -> anyhow::Result<Self> {
        tracing::debug!(?download_dir, "starting librqbit session");
        // Sibling of `download_dir` (itself `<cache_dir>/nyaa-stream/downloads`)
        // rather than nested under it, so a blanket wipe of one doesn't
        // have to know about the other's existence. Computed before
        // `download_dir` moves into `Session::new` below.
        let hls_cache_root = download_dir
            .parent()
            .map(|parent| parent.join("hls_cache"))
            .unwrap_or_else(|| download_dir.join("hls_cache"));
        let hls_jobs = HlsJobs::new(hls_cache_root);

        let session = Session::new(download_dir).await?;
        let api = Api::new(session.clone(), None);

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await?;
        let stream_addr = listener.local_addr()?;
        tracing::info!(%stream_addr, "streaming server listening");

        let router_state = StreamRouterState { api: api.clone(), stream_addr, hls_jobs: hls_jobs.clone() };
        let app = Router::new()
            .route("/stream/{torrent_id}/{file_idx}", get(stream_handler))
            .route("/hls/{torrent_id}/{file_idx}/playlist.m3u8", get(hls_playlist_handler))
            // No `.ts` suffix here: axum's router rejects a literal suffix
            // mixed with a param in the same path segment ("Only one
            // parameter is allowed per path segment") - verified live, this
            // panics at startup, not just a lint. The extension is only a
            // convention anyway; Content-Type is set explicitly below and
            // hls.js doesn't care what the segment URI looks like.
            .route("/hls/{torrent_id}/{file_idx}/{segment_index}", get(hls_segment_handler))
            .with_state(router_state)
            // hls.js loads the playlist/segments via fetch/XHR rather than
            // a plain <video src> element, which - unlike media-element
            // loading - is subject to CORS. Verified live: hls.js reported
            // a "manifestLoadError" even though the same URL loaded fine
            // via curl, since the app's origin (localhost:1420/tauri://...)
            // differs from this local server's (127.0.0.1:<port>) and we
            // sent no CORS headers at all.
            .layer(tower_http::cors::CorsLayer::permissive());
        tokio::spawn(async move {
            if let Err(err) = axum::serve(listener, app).await {
                tracing::error!(?err, "streaming server stopped");
            }
        });

        Ok(Self { session, api, stream_addr, hls_jobs })
    }

    /// Adds a torrent from a magnet link or .torrent URL and starts
    /// downloading it. librqbit prioritizes pieces for whichever file is
    /// actually being streamed once a stream is opened on it (see
    /// `stream_url`/`api_stream`), so no extra "sequential mode" flag is
    /// needed here.
    pub async fn add(&self, magnet_or_url: &str) -> anyhow::Result<AddedTorrent> {
        tracing::debug!("adding torrent");
        let add = AddTorrent::from_url(magnet_or_url);
        // Without this, re-adding a torrent whose destination file already
        // exists on disk (replaying an episode, or a thumbnail capture
        // colliding with a real download of the same release) fails
        // outright with "allow_overwrite = false" instead of resuming from
        // whatever bytes are already there - verified live.
        let opts = AddTorrentOptions {
            overwrite: true,
            ..Default::default()
        };
        let response = match self.session.add_torrent(add, Some(opts)).await {
            Ok(response) => response,
            Err(err) => {
                tracing::error!(%err, "failed to add torrent");
                return Err(err);
            }
        };

        let id = match response {
            AddTorrentResponse::Added(id, handle) => {
                tracing::info!(torrent_id = id, "torrent added");
                // A magnet link's file list/sizes aren't known until its
                // metadata arrives from peers (BEP 9) - without waiting
                // here, a request to /stream or /remux made immediately
                // after `add()` returns can 404 because the torrent isn't
                // queryable yet. Verified live: ffmpeg's very first request
                // in remux_handler consistently lost this race otherwise.
                if let Err(err) = handle.wait_until_initialized().await {
                    tracing::error!(torrent_id = id, %err, "torrent failed to initialize");
                    return Err(err);
                }
                id
            }
            AddTorrentResponse::AlreadyManaged(id, _) => {
                tracing::info!(torrent_id = id, "torrent already managed");
                id
            }
            AddTorrentResponse::ListOnly(_) => {
                tracing::error!("torrent was added in list-only mode, expected it to start");
                anyhow::bail!("torrent was added in list-only mode, expected it to start")
            }
        };

        Ok(AddedTorrent { id })
    }

    /// Removes a torrent and deletes its downloaded files. Used to clean up
    /// after a scratch download that only existed to pull a thumbnail frame
    /// out of the first few seconds of an episode - unlike a torrent the
    /// user actually chose to watch, there's no reason to keep seeding or
    /// keep the partial file around afterward.
    pub async fn remove(&self, id: TorrentId) -> anyhow::Result<()> {
        tracing::debug!(torrent_id = id, "removing torrent");
        self.hls_jobs.remove_torrent(id).await;
        self.session.delete(TorrentIdOrHash::Id(id), true).await
    }

    /// URL that streams a specific file within an already-added torrent.
    /// The local HTTP server serves it with Range support so playback can
    /// start before the whole torrent has downloaded. Raw container bytes -
    /// use `hls_playlist_url` for browser playback (see `hls_playlist_handler`'s
    /// doc comment for why).
    pub fn stream_url(&self, torrent_id: TorrentId, file_idx: usize) -> String {
        format!("http://{}/stream/{}/{}", self.stream_addr, torrent_id, file_idx)
    }

    /// URL for an HLS playlist covering a specific file within an
    /// already-added torrent - see `hls_playlist_handler`'s doc comment for
    /// why this is what the frontend's `<video>` element (via hls.js)
    /// should actually point at instead of `stream_url`. Requires a
    /// `?duration=<seconds>` query param (the frontend supplies its own
    /// estimate) to know how many segments to declare.
    pub fn hls_playlist_url(&self, torrent_id: TorrentId, file_idx: usize) -> String {
        format!("http://{}/hls/{}/{}/playlist.m3u8", self.stream_addr, torrent_id, file_idx)
    }

    /// Download progress/speed/peer-count snapshot for an in-progress
    /// torrent, polled by the frontend to show buffering feedback while
    /// mpv waits for enough data to start decoding.
    pub fn stats(&self, id: TorrentId) -> anyhow::Result<StreamStats> {
        let stats = self.api.api_stats_v1(TorrentIdOrHash::Id(id))?;
        let progress_percent = if stats.total_bytes > 0 {
            stats.progress_bytes as f64 / stats.total_bytes as f64 * 100.0
        } else {
            0.0
        };
        let (download_speed_mbps, connected_peers) = stats
            .live
            .as_ref()
            .map(|live| (live.download_speed.mbps, live.snapshot.peer_stats.live))
            .unwrap_or((0.0, 0));
        Ok(StreamStats {
            state: stats.state.to_string(),
            progress_percent,
            download_speed_mbps,
            connected_peers,
            finished: stats.finished,
            downloaded_bytes: stats.progress_bytes,
            total_bytes: stats.total_bytes,
            // `play_magnet` only ever streams file index 0 today (see
            // PLAN.md's Known gaps) - matches that assumption rather than
            // threading a real file index through this call.
            ready_seconds: self.hls_jobs.ready_seconds(id, 0),
        })
    }
}

/// Browsers refuse to play `<video src>` at all without a `Content-Type`
/// they recognize as a media type, even when the underlying codec would
/// otherwise decode fine - verified live: omitting this entirely produced
/// an immediate `MEDIA_ERR_SRC_NOT_SUPPORTED` in the frontend's `<video>`
/// regardless of the actual file. Mapped from the file's own extension
/// since librqbit doesn't otherwise expose a MIME type.
fn mime_for_filename(name: &str) -> &'static str {
    match name.rsplit('.').next().unwrap_or("").to_ascii_lowercase().as_str() {
        "mp4" | "m4v" => "video/mp4",
        "webm" => "video/webm",
        "mkv" => "video/x-matroska",
        "avi" => "video/x-msvideo",
        "mov" => "video/quicktime",
        "ts" | "m2ts" => "video/mp2t",
        _ => "application/octet-stream",
    }
}

async fn stream_handler(
    State(state): State<StreamRouterState>,
    Path((torrent_id, file_idx)): Path<(TorrentId, usize)>,
    range: Option<TypedHeader<Range>>,
) -> Result<impl axum::response::IntoResponse, axum::http::StatusCode> {
    tracing::debug!(torrent_id, file_idx, "stream request received");
    let file_stream = state.api.api_stream(TorrentIdOrHash::Id(torrent_id), file_idx).await.map_err(|err| {
        tracing::warn!(torrent_id, file_idx, %err, "stream request for unknown torrent/file");
        axum::http::StatusCode::NOT_FOUND
    })?;
    let byte_size = file_stream.len();
    let body = KnownSize::sized(file_stream, byte_size);
    let range = range.map(|TypedHeader(range)| range);

    let content_type = state
        .api
        .api_torrent_details(TorrentIdOrHash::Id(torrent_id))
        .ok()
        .and_then(|details| details.files)
        .and_then(|files| files.into_iter().nth(file_idx))
        .map(|file| mime_for_filename(&file.name))
        .unwrap_or("application/octet-stream");

    Ok(([(axum::http::header::CONTENT_TYPE, content_type)], Ranged::new(range, body)))
}

#[derive(Deserialize)]
struct PlaylistQuery {
    /// Total duration in seconds, used to compute how many segments to
    /// declare. The backend can't reliably determine this itself for a
    /// still-downloading torrent (many real releases don't declare
    /// duration until their Matroska Cues near the *end* of the file,
    /// which isn't available yet) - the frontend supplies its own estimate
    /// instead (AniList's per-episode runtime). Falls back to a generic
    /// guess if the frontend has none.
    duration: Option<f64>,
}

/// A show's typical episode length, used only when the frontend has no
/// AniList-derived estimate at all - better than refusing to build a
/// playlist, and self-corrects next time the page has real metadata.
const DEFAULT_DURATION_SECONDS: f64 = 24.0 * 60.0;

/// Serves an HLS VOD playlist for a torrent's file, built from a
/// frontend-supplied duration estimate (see `PlaylistQuery`) rather than
/// anything read from the file itself.
///
/// This - HLS via `hls.js`, replacing an earlier "remux the whole episode
/// through ffmpeg on every seek" approach - is necessary, not cosmetic:
/// verified live that a real anime release (MKV, H.264 video, E-AC-3
/// audio) fails in WebView2's `<video>` with `MEDIA_ERR_SRC_NOT_SUPPORTED`
/// even though `canPlayType` reports "probably" for every codec involved -
/// the actual blocker is that Matroska's seek index (Cues/SeekHead) is
/// commonly placed at/near the *end* of the file, which an
/// incrementally-downloading torrent can't provide up front. Segments
/// themselves are produced by `HlsJobs` (see its doc comment) rather than
/// this handler, which only ever needs to know the total segment count.
async fn hls_playlist_handler(
    Path((_torrent_id, _file_idx)): Path<(TorrentId, usize)>,
    Query(query): Query<PlaylistQuery>,
) -> impl axum::response::IntoResponse {
    let total_duration = query.duration.filter(|d| *d > 0.0).unwrap_or(DEFAULT_DURATION_SECONDS);
    let segment_count = (total_duration / SEGMENT_DURATION_SECONDS).ceil().max(1.0) as usize;

    let mut playlist = String::new();
    playlist.push_str("#EXTM3U\n");
    playlist.push_str("#EXT-X-VERSION:3\n");
    playlist.push_str(&format!("#EXT-X-TARGETDURATION:{}\n", SEGMENT_DURATION_SECONDS.ceil() as u64));
    playlist.push_str("#EXT-X-MEDIA-SEQUENCE:0\n");
    playlist.push_str("#EXT-X-PLAYLIST-TYPE:VOD\n");

    let mut remaining = total_duration;
    for index in 0..segment_count {
        let segment_len = remaining.min(SEGMENT_DURATION_SECONDS);
        playlist.push_str(&format!("#EXTINF:{segment_len:.3},\n{index}\n"));
        remaining -= segment_len;
    }
    playlist.push_str("#EXT-X-ENDLIST\n");

    ([(axum::http::header::CONTENT_TYPE, "application/vnd.apple.mpegurl")], playlist)
}

/// Serves one HLS segment from the on-disk cache produced by the
/// per-file `ffmpeg` transcode job (`HlsJobs`), starting or restarting
/// that job first if needed. See `HlsJobs`' doc comment for why this is a
/// single continuous transcode per file rather than one `ffmpeg` process
/// per segment (the old design here produced audible per-segment audio
/// discontinuities and, occasionally, outright muxer errors that dropped
/// whole segments).
async fn hls_segment_handler(
    State(state): State<StreamRouterState>,
    Path((torrent_id, file_idx, segment_index)): Path<(TorrentId, usize, usize)>,
) -> Result<impl axum::response::IntoResponse, axum::http::StatusCode> {
    // progress_percent here is a diagnostic for "seeking is slow" reports:
    // a low value at a far-forward segment_index means the wait is
    // genuinely network-bound (that part of the torrent isn't downloaded
    // yet and has to come from peers) rather than anything this server can
    // speed up on its own.
    let progress_percent = state.api.api_stats_v1(TorrentIdOrHash::Id(torrent_id)).ok().map(|stats| {
        if stats.total_bytes > 0 {
            stats.progress_bytes as f64 / stats.total_bytes as f64 * 100.0
        } else {
            0.0
        }
    });
    tracing::debug!(torrent_id, file_idx, segment_index, ?progress_percent, "hls segment request received");

    let path = state
        .hls_jobs
        .ensure_segment_available(torrent_id, file_idx, segment_index, state.stream_addr)
        .await
        .map_err(|err| {
            tracing::warn!(torrent_id, file_idx, segment_index, %err, "hls segment unavailable");
            axum::http::StatusCode::SERVICE_UNAVAILABLE
        })?;

    let bytes = tokio::fs::read(&path).await.map_err(|err| {
        tracing::error!(torrent_id, file_idx, segment_index, %err, "failed to read generated hls segment file");
        axum::http::StatusCode::INTERNAL_SERVER_ERROR
    })?;

    Ok(([(axum::http::header::CONTENT_TYPE, "video/mp2t")], bytes))
}
