use std::collections::HashMap;
use std::net::SocketAddr;
use std::path::{Path as FsPath, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::time::Duration;

use axum::extract::{Path, Query, State};
use axum::routing::get;
use axum::Router;
use axum_extra::headers::Range;
use axum_extra::TypedHeader;
use axum_range::{KnownSize, Ranged};
use enginefs::backend::{BackendConfig, TorrentBackend, TorrentHandle, TorrentSource};
use enginefs::EngineFS;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex as AsyncMutex;

/// `enginefs`'s `BackendEngineFS` keys every torrent by its info-hash
/// string rather than a numeric session id (librqbit's model, which this
/// crate used before vendoring `enginefs`'s libtorrent backend - see
/// PLAN.md's streaming-server section for why). Kept as a type alias
/// rather than a bare `String` at call sites so the meaning is documented
/// where it's used.
pub type TorrentId = String;

/// HLS segment length. 6s is Apple's low-latency recommendation.
const SEGMENT_DURATION_SECONDS: f64 = 6.0;

/// How many segments a request is allowed to sit ahead of a job's current
/// on-disk progress before that's treated as a real seek (worth killing and
/// restarting the transcode at the new offset) rather than normal
/// hls.js/browser prefetch that will be satisfied by the job's own
/// sequential progress shortly. ~2 minutes at `SEGMENT_DURATION_SECONDS`.
const RESTART_LOOKAHEAD_SEGMENTS: usize = 20;

/// How long a segment request waits for the transcode job to produce the
/// file before giving up - bounded mostly by torrent download speed, not
/// transcode speed, since `ffmpeg` blocks on `stream_handler` for
/// not-yet-downloaded bytes.
const SEGMENT_WAIT_TIMEOUT: Duration = Duration::from_secs(45);
const SEGMENT_POLL_INTERVAL: Duration = Duration::from_millis(250);

pub struct TorrentEngine {
    efs: Arc<EngineFS>,
    stream_addr: SocketAddr,
    hls_jobs: HlsJobs,
    subtitle_jobs: SubtitleJobs,
}

/// One in-progress `ffmpeg` HLS transcode for a specific torrent file -
/// see `HlsJobs` for why there's at most one of these per file and how
/// requests decide whether to reuse or restart it.
struct HlsJob {
    child: tokio::process::Child,
    dir: PathBuf,
    /// The segment index this job was told to start at (via `-ss`/
    /// `-start_number`) - segment requests below this were generated by an
    /// *earlier* job run and, if missing, need a fresh restart to fill the
    /// gap rather than waiting on this job to ever produce them.
    start_index: usize,
}

/// Tracks the single running (or most recently run) `ffmpeg` transcode job
/// per torrent file, keyed so unrelated files never block each other's
/// decisions while same-file requests serialize on one lock.
///
/// Replaces an earlier design that spawned an independent `ffmpeg -ss
/// ... -t 6 ...` process per *segment*: each one reinitialized its own AAC
/// encoder and re-based timestamps from zero, which produced audible
/// discontinuities at every segment boundary and, since `-ss` before `-i`
/// only approximately seeks without a Matroska Cues index (not available
/// on a still-downloading torrent), sometimes fed the muxer inconsistent
/// timestamps outright ("Error submitting a packet to the muxer: Invalid
/// argument" - verified live). A single continuous `ffmpeg` process per
/// file reading sequentially from byte 0 has one continuous encoder/
/// timestamp timeline for the whole episode, and its sequential HTTP reads
/// line up naturally with librqbit's own sequential piece-priority
/// download strategy instead of fighting it with scattered probe reads.
#[derive(Clone)]
struct HlsJobs {
    jobs: Arc<AsyncMutex<HashMap<(TorrentId, usize), Arc<AsyncMutex<Option<HlsJob>>>>>>,
    cache_root: PathBuf,
}

impl HlsJobs {
    fn new(cache_root: PathBuf) -> Self {
        Self { jobs: Arc::new(AsyncMutex::new(HashMap::new())), cache_root }
    }

    fn job_dir(&self, torrent_id: &TorrentId, file_idx: usize) -> PathBuf {
        self.cache_root.join(format!("{torrent_id}_{file_idx}"))
    }

    fn segment_path(&self, torrent_id: &TorrentId, file_idx: usize, segment_index: usize) -> PathBuf {
        self.job_dir(torrent_id, file_idx).join(format!("{segment_index}.ts"))
    }

    async fn key_lock(&self, torrent_id: &TorrentId, file_idx: usize) -> Arc<AsyncMutex<Option<HlsJob>>> {
        let mut jobs = self.jobs.lock().await;
        jobs.entry((torrent_id.clone(), file_idx)).or_insert_with(|| Arc::new(AsyncMutex::new(None))).clone()
    }

    /// How far into the file playback can seek and get an instant response
    /// (backed by an already-produced segment file), as a timestamp in
    /// seconds - not to be confused with raw torrent download progress.
    /// Those two track different things and can diverge a lot: a byte
    /// range can be fully downloaded while its segment still needs ffmpeg
    /// to actually process it, and a restart-at-a-seek-target can leave
    /// large already-transcoded stretches behind at a lower index than the
    /// current job's own start_index (still instantly seekable, just not
    /// "in progress" by the sense HlsJob::start_index tracks) - so this
    /// deliberately scans for the highest segment file across the whole
    /// directory, unlike the restart-decision logic elsewhere in this
    /// impl, which only looks at the *current* job's own progress.
    fn ready_seconds(&self, torrent_id: &TorrentId, file_idx: usize) -> f64 {
        let dir = self.job_dir(torrent_id, file_idx);
        let Ok(entries) = std::fs::read_dir(&dir) else {
            return 0.0;
        };
        let highest = entries
            .flatten()
            .filter_map(|entry| {
                entry.file_name().to_str().and_then(|name| name.strip_suffix(".ts")).and_then(|stem| stem.parse::<usize>().ok())
            })
            .max();
        match highest {
            Some(index) => (index + 1) as f64 * SEGMENT_DURATION_SECONDS,
            None => 0.0,
        }
    }

    /// Ensures a background transcode job is producing (or has already
    /// produced) the segment at `segment_index`, restarting it at that
    /// offset first if needed, then waits for the resulting file to land
    /// on disk.
    async fn ensure_segment_available(
        &self,
        torrent_id: &TorrentId,
        file_idx: usize,
        segment_index: usize,
        stream_addr: SocketAddr,
    ) -> anyhow::Result<PathBuf> {
        let path = self.segment_path(torrent_id, file_idx, segment_index);
        if tokio::fs::try_exists(&path).await.unwrap_or(false) {
            return Ok(path);
        }

        let job_lock = self.key_lock(torrent_id, file_idx).await;
        {
            let mut job_slot = job_lock.lock().await;
            let needs_restart = match job_slot.as_ref() {
                None => true,
                Some(job) => {
                    // Only counts files at or after this job's own
                    // start_index - the directory isn't cleared on
                    // restart, so lower-numbered segments from an earlier,
                    // already-superseded run can still be sitting there.
                    // Counting those as "progress" made a request for a
                    // fresh restart's own (not-yet-produced) target look
                    // like it was still far ahead of "current progress",
                    // triggering another pointless restart to the exact
                    // same offset - verified live: a single seek restarted
                    // the job 5+ times in a row before it was ever left
                    // alone long enough to produce a single segment.
                    let highest_existing = highest_existing_segment_from(&job.dir, job.start_index).await.unwrap_or(job.start_index);
                    // Below the current job's start: it belongs to an
                    // earlier, already-superseded run and was never
                    // produced (a backward seek into a gap a forward seek
                    // left behind). Far enough ahead of current progress
                    // that it's clearly a real seek, not prefetch the job
                    // will reach shortly on its own.
                    segment_index < job.start_index || segment_index > highest_existing + RESTART_LOOKAHEAD_SEGMENTS
                }
            };

            if needs_restart {
                if let Some(mut old) = job_slot.take() {
                    let _ = old.child.start_kill();
                    tracing::info!(torrent_id = %torrent_id, file_idx, "killed hls transcode job to restart at a new offset");
                }
                let dir = self.job_dir(torrent_id, file_idx);
                tokio::fs::create_dir_all(&dir).await?;
                let child = spawn_hls_transcode(torrent_id, file_idx, segment_index, stream_addr, &dir)?;
                *job_slot = Some(HlsJob { child, dir, start_index: segment_index });
                tracing::info!(torrent_id = %torrent_id, file_idx, segment_index, "started hls transcode job");
            }
        }

        let wait_started = tokio::time::Instant::now();
        let deadline = wait_started + SEGMENT_WAIT_TIMEOUT;
        while tokio::time::Instant::now() < deadline {
            if tokio::fs::try_exists(&path).await.unwrap_or(false) {
                // Diagnostic for "seeking is slow" reports: distinguishes a
                // slow torrent download (this job just started, most of
                // the wait was here) from a slow restart/ffmpeg-startup
                // path (this fires almost immediately after the "started
                // hls transcode job" log line above).
                tracing::debug!(
                    torrent_id = %torrent_id,
                    file_idx,
                    segment_index,
                    wait_ms = wait_started.elapsed().as_millis() as u64,
                    "hls segment became available"
                );
                return Ok(path);
            }
            {
                // Bail out early if the job already died rather than
                // waiting out the full timeout for a file it will never
                // produce (e.g. the underlying torrent stream errored).
                let mut job_slot = job_lock.lock().await;
                if let Some(job) = job_slot.as_mut() {
                    if let Ok(Some(status)) = job.child.try_wait() {
                        anyhow::bail!("hls transcode process for segment {segment_index} exited early with {status}");
                    }
                }
            }
            tokio::time::sleep(SEGMENT_POLL_INTERVAL).await;
        }
        anyhow::bail!("timed out waiting for hls segment {segment_index} to be generated")
    }

    /// Kills and forgets any transcode job for `torrent_id` (any file
    /// index) and deletes its cached segments - called when the torrent
    /// itself is removed so nothing keeps writing into a now-orphaned
    /// cache directory.
    async fn remove_torrent(&self, torrent_id: &TorrentId) {
        let mut jobs = self.jobs.lock().await;
        let keys: Vec<_> = jobs.keys().filter(|(id, _)| id == torrent_id).cloned().collect();
        for key in keys {
            if let Some(job_lock) = jobs.remove(&key) {
                let mut job_slot = job_lock.lock().await;
                if let Some(mut job) = job_slot.take() {
                    let _ = job.child.start_kill();
                    let _ = tokio::fs::remove_dir_all(&job.dir).await;
                }
            }
        }
    }
}

/// Highest `.ts` segment index present in `dir` at or after `min_index` -
/// callers pass the current job's own `start_index` so a lower-numbered
/// leftover from an earlier, already-superseded job run (the directory is
/// never cleared on restart) can't be mistaken for that job's own progress.
async fn highest_existing_segment_from(dir: &FsPath, min_index: usize) -> Option<usize> {
    let mut entries = tokio::fs::read_dir(dir).await.ok()?;
    let mut highest = None;
    while let Ok(Some(entry)) = entries.next_entry().await {
        if let Some(index) = entry
            .file_name()
            .to_str()
            .and_then(|name| name.strip_suffix(".ts"))
            .and_then(|stem| stem.parse::<usize>().ok())
        {
            if index >= min_index {
                highest = Some(highest.map_or(index, |h: usize| h.max(index)));
            }
        }
    }
    highest
}

/// Spawns the single continuous `ffmpeg` process for a torrent file's HLS
/// transcode, starting at `start_segment_index` (0 for normal sequential
/// playback from the beginning, non-zero only when restarting at a seek
/// target). Reads from `stream_handler` over loopback rather than the
/// downloaded file directly, reusing its existing Range-aware,
/// piece-priority-aware blocking reads instead of teaching `ffmpeg` about
/// librqbit's growing sparse file. Writes segments as real files
/// (`-hls_flags temp_file` renames each into place only once complete, so
/// a segment request never sees a partially-written file) rather than
/// piping to a per-request process - see `HlsJobs`' doc comment for why
/// this replaced the old one-`ffmpeg`-per-segment design.
fn spawn_hls_transcode(
    torrent_id: &TorrentId,
    file_idx: usize,
    start_segment_index: usize,
    stream_addr: SocketAddr,
    dir: &FsPath,
) -> anyhow::Result<tokio::process::Child> {
    let start_seconds = start_segment_index as f64 * SEGMENT_DURATION_SECONDS;
    let input_url = format!("http://{stream_addr}/stream/{torrent_id}/{file_idx}");
    let segment_filename = dir.join("%d.ts");
    // ffmpeg's own playlist output is discarded - hls_playlist_handler
    // still serves the frontend-duration-derived playlist described
    // there; we only want this process's segment files.
    let discarded_playlist_path = dir.join("ffmpeg_internal.m3u8");

    let mut command = tokio::process::Command::new("ffmpeg");
    command.args(["-loglevel", "warning"]);
    // Sequential playback from the start (the overwhelmingly common case)
    // deliberately omits `-ss` entirely rather than passing `-ss 0`: with
    // no Matroska Cues index available on a still-downloading torrent, any
    // `-ss` at all can make ffmpeg attempt a byte-offset seek estimate
    // instead of just reading forward from the response's first byte.
    if start_seconds > 0.0 {
        command.args(["-ss", &start_seconds.to_string()]);
    }
    command.args(["-i", &input_url]);
    command.args([
        // Real releases commonly carry an embedded subtitle track (e.g.
        // WebVTT) alongside video/audio. MPEG-TS/HLS can't carry that
        // (there's no subtitle UI here to feed it to anyway), and leaving
        // ffmpeg to auto-select "best of every stream type" made it try
        // to mux the subtitle track into the TS output anyway, which
        // spammed non-monotonic-DTS warnings and was implicated in at
        // least one dropped segment (a muxer "Invalid argument" error) -
        // verified live. Mapping exactly one video and one audio stream
        // and nothing else avoids the whole class of problem.
        "-map",
        "0:v:0",
        "-map",
        "0:a:0",
        "-sn",
        "-c:v",
        "copy",
        // Audio is always transcoded to AAC rather than copied: several
        // codecs real releases use (e.g. E-AC-3) aren't reliably muxable
        // into MPEG-TS/played back by browsers, and AAC is universally
        // supported. A single continuous encoder instance for the whole
        // file (unlike the old per-segment approach) keeps its timestamp
        // timeline continuous, which is what actually fixes the audio
        // artifacts at segment boundaries.
        "-c:a",
        "aac",
        "-f",
        "hls",
        "-hls_time",
        &SEGMENT_DURATION_SECONDS.to_string(),
        "-hls_list_size",
        "0",
        "-hls_flags",
        "temp_file+independent_segments",
        "-start_number",
        &start_segment_index.to_string(),
        "-hls_segment_filename",
    ]);
    command.arg(segment_filename.to_string_lossy().to_string());
    command.arg(discarded_playlist_path.to_string_lossy().to_string());

    let mut child = command
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| anyhow::anyhow!("failed to spawn ffmpeg for hls transcode (is it installed and on PATH?): {err}"))?;

    if let Some(stderr) = child.stderr.take() {
        // Owned copy: `torrent_id` is a caller-borrowed `&TorrentId`, but
        // this task must outlive that borrow (`tokio::spawn` requires
        // `'static`).
        let torrent_id = torrent_id.clone();
        tokio::spawn(async move {
            use tokio::io::{AsyncBufReadExt, BufReader};
            let mut lines = BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                tracing::warn!(torrent_id = %torrent_id, file_idx, ffmpeg_stderr = %line, "ffmpeg hls transcode stderr");
            }
        });
    }

    Ok(child)
}

/// One embedded subtitle track discovered in a torrent file, as reported by
/// `ffprobe` - `index` is the absolute demuxer stream index, which doubles
/// as the exact `-map 0:<index>` argument `spawn_subtitle_extraction` uses
/// and as the URL segment `subtitle_handler` serves it under, so it's never
/// renumbered anywhere along the way.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SubtitleTrack {
    pub index: usize,
    pub language: Option<String>,
    pub title: Option<String>,
}

/// Lists a torrent file's embedded subtitle tracks via `ffprobe` (reading
/// only the container header, same as `spawn_hls_transcode`'s `-i` does -
/// doesn't wait for the whole file). Doesn't require `enginefs`'s parsed
/// track list because it doesn't have one: subtitle streams aren't
/// something the streaming-server layer looks at at all, only ffmpeg/
/// ffprobe do.
async fn probe_subtitle_tracks(stream_addr: SocketAddr, torrent_id: &TorrentId, file_idx: usize) -> anyhow::Result<Vec<SubtitleTrack>> {
    let input_url = format!("http://{stream_addr}/stream/{torrent_id}/{file_idx}");
    let output = tokio::process::Command::new("ffprobe")
        .args(["-v", "error", "-print_format", "json", "-show_streams", "-select_streams", "s"])
        .arg(&input_url)
        .stdin(Stdio::null())
        .output()
        .await
        .map_err(|err| anyhow::anyhow!("failed to spawn ffprobe (is it installed and on PATH?): {err}"))?;
    if !output.status.success() {
        anyhow::bail!("ffprobe exited with {}: {}", output.status, String::from_utf8_lossy(&output.stderr));
    }

    #[derive(Deserialize)]
    struct FfprobeStream {
        index: usize,
        tags: Option<HashMap<String, String>>,
    }
    #[derive(Deserialize, Default)]
    struct FfprobeOutput {
        #[serde(default)]
        streams: Vec<FfprobeStream>,
    }
    let parsed: FfprobeOutput = serde_json::from_slice(&output.stdout)
        .map_err(|err| anyhow::anyhow!("failed to parse ffprobe output: {err}"))?;
    Ok(parsed
        .streams
        .into_iter()
        .map(|stream| {
            let mut tags = stream.tags.unwrap_or_default();
            SubtitleTrack {
                index: stream.index,
                language: tags.remove("language"),
                title: tags.remove("title"),
            }
        })
        .collect())
}

/// Tracks the single background subtitle-extraction `ffmpeg` process per
/// torrent file, keyed the same way as `HlsJobs`. Unlike `HlsJobs`, this is
/// never restarted at an offset: a subtitle track needs to cover the whole
/// episode regardless of where playback currently is, so the job is simply
/// started once (covering every track in one `ffmpeg` invocation, one
/// output per track) and left to run to completion in the background.
/// `subtitle_handler` just serves whatever bytes are on disk for a given
/// track at request time - since ffmpeg flushes WebVTT cues as it demuxes
/// them, an in-progress extraction still serves a valid (if incomplete)
/// prefix of the track rather than nothing.
///
/// Reads the same `stream_handler` input as the video `HlsJobs` transcode,
/// independently and from byte 0 regardless of the video job's own current
/// position - a real seek forward in the video leaves this job still
/// working through earlier bytes it's already read past for video. Left
/// as a known tradeoff rather than solved here: subtitle text is a tiny
/// fraction of a release's total bytes, so its share of the resulting
/// piece-priority contention is minor, and it still finishes catching up
/// well before a real download does.
#[derive(Clone)]
struct SubtitleJobs {
    jobs: Arc<AsyncMutex<HashMap<(TorrentId, usize), Arc<AsyncMutex<Option<tokio::process::Child>>>>>>,
    cache_root: PathBuf,
}

impl SubtitleJobs {
    fn new(cache_root: PathBuf) -> Self {
        Self { jobs: Arc::new(AsyncMutex::new(HashMap::new())), cache_root }
    }

    fn job_dir(&self, torrent_id: &TorrentId, file_idx: usize) -> PathBuf {
        self.cache_root.join(format!("{torrent_id}_{file_idx}"))
    }

    fn track_path(&self, torrent_id: &TorrentId, file_idx: usize, stream_index: usize) -> PathBuf {
        self.job_dir(torrent_id, file_idx).join(format!("{stream_index}.vtt"))
    }

    /// Starts the extraction job for `tracks` if one hasn't already been
    /// started for this file - a no-op on every call after the first
    /// (including once the job has already finished), since there's never
    /// a reason to restart it.
    async fn ensure_running(&self, torrent_id: &TorrentId, file_idx: usize, tracks: &[SubtitleTrack], stream_addr: SocketAddr) -> anyhow::Result<()> {
        if tracks.is_empty() {
            return Ok(());
        }
        let job_lock = {
            let mut jobs = self.jobs.lock().await;
            jobs.entry((torrent_id.clone(), file_idx)).or_insert_with(|| Arc::new(AsyncMutex::new(None))).clone()
        };
        let mut job_slot = job_lock.lock().await;
        if job_slot.is_some() {
            return Ok(());
        }
        let dir = self.job_dir(torrent_id, file_idx);
        tokio::fs::create_dir_all(&dir).await?;
        let child = spawn_subtitle_extraction(torrent_id, file_idx, tracks, stream_addr, &dir)?;
        *job_slot = Some(child);
        tracing::info!(torrent_id = %torrent_id, file_idx, track_count = tracks.len(), "started subtitle extraction job");
        Ok(())
    }

    /// Kills and forgets any extraction job for `torrent_id` (any file
    /// index) and deletes its cached tracks - mirrors `HlsJobs::remove_torrent`.
    async fn remove_torrent(&self, torrent_id: &TorrentId) {
        let mut jobs = self.jobs.lock().await;
        let keys: Vec<_> = jobs.keys().filter(|(id, _)| id == torrent_id).cloned().collect();
        for key in keys {
            if let Some(job_lock) = jobs.remove(&key) {
                let mut job_slot = job_lock.lock().await;
                if let Some(mut child) = job_slot.take() {
                    let _ = child.start_kill();
                }
                let _ = tokio::fs::remove_dir_all(self.job_dir(&key.0, key.1)).await;
            }
        }
    }
}

/// Spawns one `ffmpeg` process that extracts every track in `tracks` to its
/// own WebVTT file in `dir` (named `<stream_index>.vtt`), in a single pass
/// over the input - one `-map`/`-c:s webvtt` output per track, all reading
/// the same demux instead of one process per track re-reading the file
/// from scratch each time.
fn spawn_subtitle_extraction(
    torrent_id: &TorrentId,
    file_idx: usize,
    tracks: &[SubtitleTrack],
    stream_addr: SocketAddr,
    dir: &FsPath,
) -> anyhow::Result<tokio::process::Child> {
    let input_url = format!("http://{stream_addr}/stream/{torrent_id}/{file_idx}");
    let mut command = tokio::process::Command::new("ffmpeg");
    command.args(["-loglevel", "warning", "-i", &input_url]);
    for track in tracks {
        command.args(["-map", &format!("0:{}", track.index), "-c:s", "webvtt", "-f", "webvtt"]);
        command.arg(dir.join(format!("{}.vtt", track.index)).to_string_lossy().to_string());
    }

    let mut child = command
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| anyhow::anyhow!("failed to spawn ffmpeg for subtitle extraction (is it installed and on PATH?): {err}"))?;

    if let Some(stderr) = child.stderr.take() {
        let torrent_id = torrent_id.clone();
        tokio::spawn(async move {
            use tokio::io::{AsyncBufReadExt, BufReader};
            let mut lines = BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                tracing::warn!(torrent_id = %torrent_id, file_idx, ffmpeg_stderr = %line, "ffmpeg subtitle extraction stderr");
            }
        });
    }

    Ok(child)
}

pub struct AddedTorrent {
    pub id: TorrentId,
}

#[derive(Clone)]
struct StreamRouterState {
    efs: Arc<EngineFS>,
    stream_addr: SocketAddr,
    hls_jobs: HlsJobs,
    subtitle_jobs: SubtitleJobs,
}

/// Trimmed-down mirror of librqbit's `TorrentStats` - mirrors Stremio's own
/// streaming-server statistics endpoint (`GET /:infoHash/stats.json`,
/// see `reference/stremio-core`'s `models::streaming_server`), which the
/// player UI polls to show download progress/speed/peers while a stream is
/// buffering, rather than leaving the user staring at a blank window with
/// no feedback while mpv waits for enough data to start decoding.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StreamStats {
    /// "initializing" | "live" | "paused" | "error"
    pub state: String,
    pub progress_percent: f64,
    /// Despite the name, librqbit's underlying `Speed::mbps` field is
    /// actually MiB/s (see its `Display` impl) - mirrored as-is here.
    pub download_speed_mbps: f64,
    pub connected_peers: u32,
    pub finished: bool,
    /// Raw byte counts (alongside `progress_percent`) so the frontend can
    /// port stremio-web's own weighted buffering-readiness score
    /// (`useStatistics.ts`'s `getLoadingProgress`: peers/downloaded-vs-
    /// threshold/speed, not just raw completion percent) rather than a
    /// cruder "% of the whole file" estimate.
    pub downloaded_bytes: u64,
    pub total_bytes: u64,
    /// How far into the file (in seconds) HLS segments have actually been
    /// produced and are ready for an instant seek - see
    /// `HlsJobs::ready_seconds`'s doc comment for why this isn't the same
    /// thing as `progress_percent`. Frontend seek-bar highlight should use
    /// this, not `progress_percent`, for "can I seek here instantly".
    pub ready_seconds: f64,
}

impl TorrentEngine {
    /// Starts an `enginefs` libtorrent-backend engine rooted at
    /// `download_dir` and a local HTTP server that serves torrent file
    /// bytes with Range support, mirroring Stremio's local streaming
    /// server. Disk-backed (not `enginefs`'s memory-only mode) so partial
    /// downloads survive an app restart, matching this crate's previous
    /// librqbit-based behavior - see PLAN.md's streaming-server section.
    pub async fn start(download_dir: PathBuf) -> anyhow::Result<Self> {
        tracing::debug!(?download_dir, "starting enginefs libtorrent backend");
        // Sibling of `download_dir` (itself `<cache_dir>/nyaa-stream/downloads`)
        // rather than nested under it, so a blanket wipe of one doesn't
        // have to know about the other's existence. Computed before
        // `download_dir` moves into `LibtorrentBackend::new_disk_backed` below.
        let hls_cache_root = download_dir
            .parent()
            .map(|parent| parent.join("hls_cache"))
            .unwrap_or_else(|| download_dir.join("hls_cache"));
        let hls_jobs = HlsJobs::new(hls_cache_root);
        let subtitles_cache_root = download_dir
            .parent()
            .map(|parent| parent.join("subtitles_cache"))
            .unwrap_or_else(|| download_dir.join("subtitles_cache"));
        let subtitle_jobs = SubtitleJobs::new(subtitles_cache_root);
        let cache_dir = download_dir
            .parent()
            .map(|parent| parent.join("engine_cache"))
            .unwrap_or_else(|| download_dir.join("engine_cache"));

        let config = BackendConfig::default();
        let backend = enginefs::backend::libtorrent::LibtorrentBackend::new_disk_backed(download_dir.clone(), config)?;
        let efs: Arc<EngineFS> = Arc::new(EngineFS::new_with_backend(backend, HashMap::new(), cache_dir, download_dir));

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await?;
        let stream_addr = listener.local_addr()?;
        tracing::info!(%stream_addr, "streaming server listening");

        let router_state =
            StreamRouterState { efs: efs.clone(), stream_addr, hls_jobs: hls_jobs.clone(), subtitle_jobs: subtitle_jobs.clone() };
        let app = Router::new()
            .route("/stream/{torrent_id}/{file_idx}", get(stream_handler))
            .route("/hls/{torrent_id}/{file_idx}/playlist.m3u8", get(hls_playlist_handler))
            // No `.ts` suffix here: axum's router rejects a literal suffix
            // mixed with a param in the same path segment ("Only one
            // parameter is allowed per path segment") - verified live, this
            // panics at startup, not just a lint. The extension is only a
            // convention anyway; Content-Type is set explicitly below and
            // hls.js doesn't care what the segment URI looks like.
            .route("/hls/{torrent_id}/{file_idx}/{segment_index}", get(hls_segment_handler))
            .route("/subtitles/{torrent_id}/{file_idx}/{stream_index}", get(subtitle_handler))
            .with_state(router_state)
            // hls.js loads the playlist/segments via fetch/XHR rather than
            // a plain <video src> element, which - unlike media-element
            // loading - is subject to CORS. Verified live: hls.js reported
            // a "manifestLoadError" even though the same URL loaded fine
            // via curl, since the app's origin (localhost:1420/tauri://...)
            // differs from this local server's (127.0.0.1:<port>) and we
            // sent no CORS headers at all.
            .layer(tower_http::cors::CorsLayer::permissive());
        tokio::spawn(async move {
            if let Err(err) = axum::serve(listener, app).await {
                tracing::error!(?err, "streaming server stopped");
            }
        });

        Ok(Self { efs, stream_addr, hls_jobs, subtitle_jobs })
    }

    /// Adds a torrent from a magnet link or .torrent URL and starts
    /// downloading it. `enginefs`'s libtorrent backend prioritizes pieces
    /// for whichever file is actually being streamed once a stream is
    /// opened on it (its `LibtorrentPlaybackCoordinator`, driven by
    /// `refresh_hls_playback` in `stream_handler`/`hls_segment_handler`
    /// below), so no extra "sequential mode" flag is needed here.
    pub async fn add(&self, magnet_or_url: &str) -> anyhow::Result<AddedTorrent> {
        tracing::debug!("adding torrent");
        let engine = self.efs.add_torrent(TorrentSource::Url(magnet_or_url.to_string()), None).await.map_err(|err| {
            tracing::error!(%err, "failed to add torrent");
            err
        })?;
        let id = engine.info_hash.clone();
        tracing::info!(torrent_id = %id, "torrent added");
        Ok(AddedTorrent { id })
    }

    /// Removes a torrent from the engine and deletes our own HLS transcode
    /// cache for it. Used to clean up after a scratch download that only
    /// existed to pull a thumbnail frame out of the first few seconds of an
    /// episode - unlike a torrent the user actually chose to watch, there's
    /// no reason to keep seeding or keep the partial file around afterward.
    ///
    /// Note: unlike this crate's previous librqbit-based `remove`,
    /// `enginefs`'s libtorrent backend's own `remove_torrent` does not
    /// delete the torrent's downloaded files from disk (it calls
    /// libtorrent's `remove_torrent` with `delete_files = false` -
    /// verified in `enginefs`'s vendored source) - only our own HLS cache
    /// is guaranteed cleaned up here.
    pub async fn remove(&self, id: TorrentId) -> anyhow::Result<()> {
        tracing::debug!(torrent_id = %id, "removing torrent");
        self.hls_jobs.remove_torrent(&id).await;
        self.subtitle_jobs.remove_torrent(&id).await;
        self.efs.remove_engine(&id).await;
        self.efs.get_backend().remove_torrent(&id).await
    }

    /// URL that streams a specific file within an already-added torrent.
    /// The local HTTP server serves it with Range support so playback can
    /// start before the whole torrent has downloaded. Raw container bytes -
    /// use `hls_playlist_url` for browser playback (see `hls_playlist_handler`'s
    /// doc comment for why).
    pub fn stream_url(&self, torrent_id: &TorrentId, file_idx: usize) -> String {
        format!("http://{}/stream/{}/{}", self.stream_addr, torrent_id, file_idx)
    }

    /// URL for an HLS playlist covering a specific file within an
    /// already-added torrent - see `hls_playlist_handler`'s doc comment for
    /// why this is what the frontend's `<video>` element (via hls.js)
    /// should actually point at instead of `stream_url`. Requires a
    /// `?duration=<seconds>` query param (the frontend supplies its own
    /// estimate) to know how many segments to declare.
    pub fn hls_playlist_url(&self, torrent_id: &TorrentId, file_idx: usize) -> String {
        format!("http://{}/hls/{}/{}/playlist.m3u8", self.stream_addr, torrent_id, file_idx)
    }

    /// Lists a torrent file's embedded subtitle tracks and kicks off (if not
    /// already running) the background job that extracts all of them to
    /// WebVTT - see `SubtitleJobs`' doc comment for why that's a
    /// fire-and-forget job rather than something awaited here. Safe to call
    /// repeatedly (e.g. once per player mount): the extraction job itself is
    /// only ever started once per file.
    pub async fn list_subtitle_tracks(&self, torrent_id: &TorrentId, file_idx: usize) -> anyhow::Result<Vec<SubtitleTrack>> {
        let tracks = probe_subtitle_tracks(self.stream_addr, torrent_id, file_idx).await?;
        self.subtitle_jobs.ensure_running(torrent_id, file_idx, &tracks, self.stream_addr).await?;
        Ok(tracks)
    }

    /// URL a `<track>` element can fetch a specific subtitle track's WebVTT
    /// content from - `stream_index` is the same absolute demuxer index
    /// `SubtitleTrack::index` reports.
    pub fn subtitle_url(&self, torrent_id: &TorrentId, file_idx: usize, stream_index: usize) -> String {
        format!("http://{}/subtitles/{}/{}/{}", self.stream_addr, torrent_id, file_idx, stream_index)
    }

    /// Download progress/speed/peer-count snapshot for an in-progress
    /// torrent, polled by the frontend to show buffering feedback while
    /// mpv waits for enough data to start decoding.
    pub async fn stats(&self, id: &TorrentId) -> anyhow::Result<StreamStats> {
        let engine = self.efs.get_engine(id).await.ok_or_else(|| anyhow::anyhow!("unknown torrent {id}"))?;
        let stats = engine.get_statistics().await;

        let total_bytes: u64 = stats.files.iter().map(|f| f.length).sum();
        let downloaded_bytes: u64 = stats.files.iter().map(|f| f.downloaded).sum();
        let progress_percent = if total_bytes > 0 { downloaded_bytes as f64 / total_bytes as f64 * 100.0 } else { 0.0 };
        // `enginefs::backend::EngineStats::download_speed` is bytes/sec,
        // unlike librqbit's `Speed::mbps` (MiB/s) this field previously
        // mirrored - converted here so `StreamStats`'s documented unit
        // (MiB/s, consumed by the frontend) doesn't silently change.
        let download_speed_mbps = stats.download_speed / (1024.0 * 1024.0);
        let state = if !stats.has_metadata {
            "initializing"
        } else if stats.swarm_paused {
            "paused"
        } else {
            "live"
        };

        Ok(StreamStats {
            state: state.to_string(),
            progress_percent,
            download_speed_mbps,
            connected_peers: stats.peers as u32,
            finished: stats.is_finished,
            downloaded_bytes,
            total_bytes,
            // `play_magnet` only ever streams file index 0 today (see
            // PLAN.md's Known gaps) - matches that assumption rather than
            // threading a real file index through this call.
            ready_seconds: self.hls_jobs.ready_seconds(id, 0),
        })
    }
}

/// Browsers refuse to play `<video src>` at all without a `Content-Type`
/// they recognize as a media type, even when the underlying codec would
/// otherwise decode fine - verified live: omitting this entirely produced
/// an immediate `MEDIA_ERR_SRC_NOT_SUPPORTED` in the frontend's `<video>`
/// regardless of the actual file. Mapped from the file's own extension
/// since librqbit doesn't otherwise expose a MIME type.
fn mime_for_filename(name: &str) -> &'static str {
    match name.rsplit('.').next().unwrap_or("").to_ascii_lowercase().as_str() {
        "mp4" | "m4v" => "video/mp4",
        "webm" => "video/webm",
        "mkv" => "video/x-matroska",
        "avi" => "video/x-msvideo",
        "mov" => "video/quicktime",
        "ts" | "m2ts" => "video/mp2t",
        _ => "application/octet-stream",
    }
}

async fn stream_handler(
    State(state): State<StreamRouterState>,
    Path((torrent_id, file_idx)): Path<(TorrentId, usize)>,
    range: Option<TypedHeader<Range>>,
) -> Result<impl axum::response::IntoResponse, axum::http::StatusCode> {
    tracing::debug!(torrent_id = %torrent_id, file_idx, "stream request received");
    let engine = state.efs.get_engine(&torrent_id).await.ok_or_else(|| {
        tracing::warn!(torrent_id = %torrent_id, file_idx, "stream request for unknown torrent");
        axum::http::StatusCode::NOT_FOUND
    })?;

    // Refreshes this file's HLS playback lease (resumes the torrent if
    // paused, reprioritizes pieces toward it) - a no-op-cheap early return
    // on the common case of a repeat request for the file already being
    // watched. See PLAN.md's streaming-server section / `playback.rs`'s
    // `LibtorrentPlaybackCoordinator` for why this needs to be called on
    // every request rather than once when the stream starts.
    state.efs.refresh_hls_playback(&torrent_id, file_idx, "raw-stream").await;

    // priority 128: a normal foreground direct-playback read (not the
    // internal-probe/background sentinels `Engine::get_file` treats 255/0
    // as - see `enginefs::engine::Engine::get_file`'s doc comment).
    let file_handle = engine.get_file(file_idx, 0, 128).await.ok_or_else(|| {
        tracing::warn!(torrent_id = %torrent_id, file_idx, "stream request for unknown file index");
        axum::http::StatusCode::NOT_FOUND
    })?;
    let byte_size = file_handle.size;
    let body = KnownSize::sized(file_handle, byte_size);
    let range = range.map(|TypedHeader(range)| range);

    let content_type = engine
        .handle
        .get_files()
        .await
        .into_iter()
        .nth(file_idx)
        .map(|file| mime_for_filename(&file.name))
        .unwrap_or("application/octet-stream");

    Ok(([(axum::http::header::CONTENT_TYPE, content_type)], Ranged::new(range, body)))
}

#[derive(Deserialize)]
struct PlaylistQuery {
    /// Total duration in seconds, used to compute how many segments to
    /// declare. The backend can't reliably determine this itself for a
    /// still-downloading torrent (many real releases don't declare
    /// duration until their Matroska Cues near the *end* of the file,
    /// which isn't available yet) - the frontend supplies its own estimate
    /// instead (AniList's per-episode runtime). Falls back to a generic
    /// guess if the frontend has none.
    duration: Option<f64>,
}

/// A show's typical episode length, used only when the frontend has no
/// AniList-derived estimate at all - better than refusing to build a
/// playlist, and self-corrects next time the page has real metadata.
const DEFAULT_DURATION_SECONDS: f64 = 24.0 * 60.0;

/// Serves an HLS VOD playlist for a torrent's file, built from a
/// frontend-supplied duration estimate (see `PlaylistQuery`) rather than
/// anything read from the file itself.
///
/// This - HLS via `hls.js`, replacing an earlier "remux the whole episode
/// through ffmpeg on every seek" approach - is necessary, not cosmetic:
/// verified live that a real anime release (MKV, H.264 video, E-AC-3
/// audio) fails in WebView2's `<video>` with `MEDIA_ERR_SRC_NOT_SUPPORTED`
/// even though `canPlayType` reports "probably" for every codec involved -
/// the actual blocker is that Matroska's seek index (Cues/SeekHead) is
/// commonly placed at/near the *end* of the file, which an
/// incrementally-downloading torrent can't provide up front. Segments
/// themselves are produced by `HlsJobs` (see its doc comment) rather than
/// this handler, which only ever needs to know the total segment count.
async fn hls_playlist_handler(
    Path((_torrent_id, _file_idx)): Path<(TorrentId, usize)>,
    Query(query): Query<PlaylistQuery>,
) -> impl axum::response::IntoResponse {
    let total_duration = query.duration.filter(|d| *d > 0.0).unwrap_or(DEFAULT_DURATION_SECONDS);
    let segment_count = (total_duration / SEGMENT_DURATION_SECONDS).ceil().max(1.0) as usize;

    let mut playlist = String::new();
    playlist.push_str("#EXTM3U\n");
    playlist.push_str("#EXT-X-VERSION:3\n");
    playlist.push_str(&format!("#EXT-X-TARGETDURATION:{}\n", SEGMENT_DURATION_SECONDS.ceil() as u64));
    playlist.push_str("#EXT-X-MEDIA-SEQUENCE:0\n");
    playlist.push_str("#EXT-X-PLAYLIST-TYPE:VOD\n");

    let mut remaining = total_duration;
    for index in 0..segment_count {
        let segment_len = remaining.min(SEGMENT_DURATION_SECONDS);
        playlist.push_str(&format!("#EXTINF:{segment_len:.3},\n{index}\n"));
        remaining -= segment_len;
    }
    playlist.push_str("#EXT-X-ENDLIST\n");

    ([(axum::http::header::CONTENT_TYPE, "application/vnd.apple.mpegurl")], playlist)
}

/// Serves one HLS segment from the on-disk cache produced by the
/// per-file `ffmpeg` transcode job (`HlsJobs`), starting or restarting
/// that job first if needed. See `HlsJobs`' doc comment for why this is a
/// single continuous transcode per file rather than one `ffmpeg` process
/// per segment (the old design here produced audible per-segment audio
/// discontinuities and, occasionally, outright muxer errors that dropped
/// whole segments).
async fn hls_segment_handler(
    State(state): State<StreamRouterState>,
    Path((torrent_id, file_idx, segment_index)): Path<(TorrentId, usize, usize)>,
) -> Result<impl axum::response::IntoResponse, axum::http::StatusCode> {
    tracing::debug!(torrent_id = %torrent_id, file_idx, segment_index, "hls segment request received");

    // Keeps this file's playback lease alive and its pieces prioritized
    // (`LibtorrentPlaybackCoordinator::refresh_hls`) - hls.js polls this
    // endpoint roughly every `SEGMENT_DURATION_SECONDS`, which is what
    // actually keeps the torrent resumed/prioritized while playing; the
    // one-time ffmpeg request to `stream_handler` when a transcode job
    // starts (see `spawn_hls_transcode`) isn't enough on its own since
    // that request is made once per continuous ffmpeg process, not once
    // per segment poll.
    state.efs.refresh_hls_playback(&torrent_id, file_idx, "hls-segment").await;

    let path = state
        .hls_jobs
        .ensure_segment_available(&torrent_id, file_idx, segment_index, state.stream_addr)
        .await
        .map_err(|err| {
            tracing::warn!(torrent_id = %torrent_id, file_idx, segment_index, %err, "hls segment unavailable");
            axum::http::StatusCode::SERVICE_UNAVAILABLE
        })?;

    let bytes = tokio::fs::read(&path).await.map_err(|err| {
        tracing::error!(torrent_id = %torrent_id, file_idx, segment_index, %err, "failed to read generated hls segment file");
        axum::http::StatusCode::INTERNAL_SERVER_ERROR
    })?;

    Ok(([(axum::http::header::CONTENT_TYPE, "video/mp2t")], bytes))
}

/// Serves whatever bytes the background subtitle-extraction job (see
/// `SubtitleJobs`) has written for one track so far. Unlike
/// `hls_segment_handler`, this never waits for or restarts anything - the
/// job was already started by `list_subtitle_tracks`, and a `<track>`
/// element's one-shot fetch just gets a (possibly still-growing, but valid)
/// prefix of the full WebVTT file if extraction hasn't finished yet.
async fn subtitle_handler(
    State(state): State<StreamRouterState>,
    Path((torrent_id, file_idx, stream_index)): Path<(TorrentId, usize, usize)>,
) -> Result<impl axum::response::IntoResponse, axum::http::StatusCode> {
    let path = state.subtitle_jobs.track_path(&torrent_id, file_idx, stream_index);
    let bytes = tokio::fs::read(&path).await.map_err(|err| {
        tracing::warn!(torrent_id = %torrent_id, file_idx, stream_index, %err, "subtitle track unavailable");
        axum::http::StatusCode::NOT_FOUND
    })?;
    Ok(([(axum::http::header::CONTENT_TYPE, "text/vtt")], bytes))
}
